### ISSUE TITLE
Library Maintenance

### ISSUE THREAD

**Issue by alleypa** [ngbracket/ngx-layout#13]
@DuncanFaulkner, 

Many thanks for supporting Angular Flex and taking over the maintenance of the library. Will you be maintaining this library for the long haul. Infinity maybe.

**Comment by DuncanFaulkner** [comment]
Hopefully, that's the plan at the moment, it's still pulling 300k downloads on NPM so there is still a demand for this library I just need to spread the word that it has a new home and a new name.
