### ISSUE TITLE
2 High severity vulnerabilities

### ISSUE THREAD

**Issue by yvesguilherme** [ngbracket/ngx-layout#16]
Hello, how are you?

I'm using Angular ^15.2.0 and when I was installing this library 'npm i @ngbracket/ngx-layout@15.1.3', my console returned this problem:

![image](https://user-images.githubusercontent.com/22429592/228894367-27d333de-b9ea-45ce-a34e-0a759aae0be5.png)

I typed 'npm audit fix' and this command returned this problem:

![image](https://user-images.githubusercontent.com/22429592/228894910-03a609f5-7b21-4ae2-b55c-26a122ef7656.png)

Can you solve this problem, please?
Congratulations on this library... The Google team let me down too much... 
Hugs!

**Comment by DuncanFaulkner** [comment]
@yvesguilherme 
Hi I'm not able to reproduce this error, it looks like the error is referring to Webpack as the issue

**Comment by robotikz** [comment]
Hi, can u create a very simple repository with the issue? 
Some additional info about your environment would be helpful.

**Comment by DuncanFaulkner** [comment]
closing for now, but can reopen if required
