### ISSUE TITLE
Error when using FlexLayoutServerModule

### ISSUE THREAD

**Issue by Alexi996** [ngbracket/ngx-layout#44]
I have just created a project which uses Angular Universal and FlexLayoutServerModule from '@ngbracket/ngx-layout/server'.

When I add FlexLayoutServerModule, I'm getting following error:

./node_modules/@angular/platform-server/fesm2022/platform-server.mjs:15:0-27 - Error: Module not found: Error: Can't resolve 'url' in 'D:\"path-to-project"\node_modules\@angular\platform-server\fesm2022'   

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
        - install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "url": false }

And the project doesn't compile.
Unfortunately, I wasn't able to find the solution online.

I also tried to use FlexLayoutModule  with SSR, but when I'm using FlexLayoutModule in SSR mode, the app is compiling without error, but the page layout is being aligned properly after the page loading is finished, so, it is creating a noticeable lack of rendering speed, especially in those sections which are present in every page, like Nav Menu, Footer, etc...

Here's the data about my Angular, Node and packages versions:

![image](https://github.com/ngbracket/ngx-layout/assets/47609114/39b5ed98-941a-45d0-b358-b1cbbb6c134c)

Feel free to ask me to provide other data if needed.

**Comment by DuncanFaulkner** [comment]
@Alexi996 can you try the SSR app in this project,

**Comment by Alexi996** [comment]
@DuncanFaulkner Not sure what exactly you're asking me. Do you mean SSR app using @ngbracket FlexLayoutServerModule , or something else?

**Comment by DuncanFaulkner** [comment]
Sorry I posted too early by mistake

**Comment by Alexi996** [comment]
Hey, @DuncanFaulkner! Yeah, it works correctly. I'll try to review my stuff and fix it. You can close the issue. Thank You a lot! :)

**Comment by DuncanFaulkner** [comment]
no problem, thanks for raising the ticket
