### ISSUE TITLE
Support for Angular 17

### ISSUE THREAD

**Issue by dickerpulli** [ngbracket/ngx-layout#45]
What about upgrading to Angular 17?
Is the current version 6.1.2 compatible to Angular 17?

Thanks.

**Comment by DuncanFaulkner** [comment]
@dickerpulli it's on my to-do list - just not got around to it just yet

**Comment by DuncanFaulkner** [comment]
@dickerpulli I have just published this for version 17, please can you try this and let me know if you have any issues.
