### ISSUE TITLE
ngClass API broken in latest AngularBuild (17.0.5)?

### ISSUE THREAD

**Issue by mnesser** [ngbracket/ngx-layout#49]
# Bug Report

#### What is the expected behaviour?
ngClass.lt-md="classX" should add the class when the screen size matches the conditon (screen and (min-width: 1280px))

#### What is the current behaviour?
page not loading and and a error is logged in the console
error: TypeError: this._renderer.addClass is not a function)

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.
Unable to provide StackBlitz
The entrypoint for '@ngbracket/ngx-layout' could not successfully be resolved. The file '/turbo_modules/@ngbracket/ngx-layout@16.1.3/index.js' does not exist. Please log an issue with the package author or check for an updated version of the package.

**Comment by DuncanFaulkner** [comment]
Thanks for the bug report, not sure what's happening here, I might need to update the package to the latest version of Angular to see if I can recreate it.

**Comment by DuncanFaulkner** [comment]
@mnesser I just updated the project locally and it looks like something has changed in the NgClass, will need to investigate further to find out what's going on will keep you posted.

**Comment by DuncanFaulkner** [comment]
@mnesser It looks like the Angular team has removed some parameters from NgClass that were only used by Angular Flex-Layout.
https://github.com/angular/angular/pull/53831
