### ISSUE TITLE
readme wording change

### ISSUE THREAD

**Issue by cdibbs** [ngbracket/ngx-layout#54]
# Proposal
#### What is the summary of the proposal?

Change the language of the readme to better communicate the intention of continuing the original @angular/flex-layout project so as to avoid hindering its own success. People can "throw in" with this project rather than the broader community spawning a million custom, internal libraries of their own.

#### What is the proposal?

Change the first sentence of the readme to something like: "This project is a continuation of the original, open-source Angular project, `@angular/flex-layout`, which is no longer maintained. Please consider collaborating with us rather than creating your own, private flex libraries. Many hands make light work!"

#### Is there anything else we should know?

I had a teammate express confusion about that first sentence: "the Angular team no longer publishes new releases of this project." It overshadows the rest of the document. They thought it meant this repo itself was no longer maintained and was arguing in favor of "rolling our own" flex library internally.

Thank you for your work on this!

**Comment by DuncanFaulkner** [comment]
Thanks I will update the read me file - looking to do a version 18 release soon

**Comment by DuncanFaulkner** [comment]
new version released - changes to wording as suggested - thanks for your input on this, much appreciated 
https://www.npmjs.com/package/@ngbracket/ngx-layout/v/18.0.0

**Comment by cdibbs** [comment]
Hey @DuncanFaulkner - it looks like the wording changes didn't make it in. Readme shows as not updated in 7 mo. Thanks again!

**Comment by DuncanFaulkner** [comment]
DOH! I I will update the reamdme, I added it to the reamdme that gets pushed up to npm but forgot the GitHub reamdme, thanks for spotting this
