### ISSUE TITLE
angular 18 support

### ISSUE THREAD

**Issue by omidpaydar** [ngbracket/ngx-layout#55]
any plan for support angular 18?

**Comment by DuncanFaulkner** [comment]
Hi, yes working it should be soon

**Comment by DuncanFaulkner** [comment]
Hopefully it shouldn't be much longer, I'm having an issue after upgrading to 18.1 hope to fix and release soon

**Comment by tran4o** [comment]
This branch does work with 18, also 18.1
https://github.com/jtc10005/ngx-flex-layout#readme

**Comment by DuncanFaulkner** [comment]
version 18 has been released
This uses angular 18.1
https://www.npmjs.com/package/@ngbracket/ngx-layout/v/18.0.0

**Comment by DuncanFaulkner** [comment]
released

**Comment by clark-stevenson** [comment]
@DuncanFaulkner  Thank you for your ongoing support of this library 😎
